### ISSUE TITLE
Wrong git tag breaks shards

### ISSUE THREAD

**Issue by endorama** [icyleaf/colorful.cr#2]
Hello, trying to install your shard the `crystal deps` command breaks because it can't find the tag `v0.1.0`.

This is probably related to [this bug](https://github.com/crystal-lang/shards/issues/108):
> The problem are the tags. Shards is looking for a v0.8 tag but it can't be found because it's 0.8 (missing a leading v). [...]

I can specify manually the tag, so it's not critical, but could you fix this? Thanks :)

**Comment by icyleaf** [comment]
Done, renamed `0.1.0` to `v0.1.0`

**Comment by endorama** [comment]
😎 thanks!
